import toml
import glob
import h5py
import numpy as np
from os import environ

TAMBOSIM_PATH = environ['TAMBOSIM_PATH']
TAMBO_DATA_PATH = environ['TAMBO_DATA_PATH']

checkpoint inject_neutrinos:
    input:
        injection_config = lambda wildcards: f'{TAMBOSIM_PATH}/resources/configuration_examples/{wildcards.injection_config}.toml'
    output:
        outfile = f"{TAMBO_DATA_PATH}/{{injection_config}}/injection/{{injection_config}}_{{injection_simset}}_{{injection_subsimset}}.jld2"
    resources:
        cpus_per_task=1,
        mem_mb=10000,
        slurm_partition="sapphire,shared",
        runtime=8*60
    shell: # Purge old shower files and inject neutrinos
        f"""
        rm -rf {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/showers/{{wildcards.injection_simset}}_{{wildcards.injection_subsimset}}/shower_*_* ; \
        julia {TAMBOSIM_PATH}/scripts/0_simulate_events/inject_neutrinos.jl \
        --config {{input.injection_config}} \
        --simset {{wildcards.injection_simset}} \
        --subsimset {{wildcards.injection_subsimset}} \
        --output {{output.outfile}}
        """

rule take_shower:
    input:
        injection_config = lambda wildcards: f"{TAMBOSIM_PATH}/resources/configuration_examples/{wildcards.injection_config}.toml",
        injection_file = lambda wildcards: f"{TAMBO_DATA_PATH}/{wildcards.injection_config}/injection/{wildcards.injection_config}_{wildcards.injection_simset}_{wildcards.injection_subsimset}.jld2"
    output:
        f"{TAMBO_DATA_PATH}/{{injection_config}}/showers/{{injection_simset}}_{{injection_subsimset}}/shower_{{take_shower_proposal_id}}_{{take_shower_decay_id}}/particles/particles.parquet"
    resources:
        cpus_per_task=1,
        mem_mb=10000,
        slurm_partition="sapphire,shared",
        runtime=24*60
    shell:
        f"""
        julia {TAMBOSIM_PATH}/scripts/0_simulate_events/take_shower.jl \
        --config {TAMBOSIM_PATH}/resources/configuration_examples/{{wildcards.injection_config}}.toml \
        --injection_file {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/injection/{{wildcards.injection_config}}_{{wildcards.injection_simset}}_{{wildcards.injection_subsimset}}.jld2 \
        --shower_dir {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/showers/{{wildcards.injection_simset}}_{{wildcards.injection_subsimset}}/ \
        --proposal_id {{wildcards.take_shower_proposal_id}} \
        --decay_id {{wildcards.take_shower_decay_id}} \
        --simset {{wildcards.injection_simset}} \
        --subsimset {{wildcards.injection_subsimset}}
        """


def get_particle_ids(wildcards):
    with h5py.File(f"{TAMBO_DATA_PATH}/{wildcards.injection_config}/injection/{wildcards.injection_config}_{wildcards.injection_simset}_{wildcards.injection_subsimset}.jld2") as f:
        particle_ids = f["corsika_indices"][:]
        return list(np.array([particle_ids['1'], particle_ids['2']]).T) # Yikes

def get_injection_files(wildcards):
    # If the injection file doesn't exist, then the injection should be specified as the input file
    # If the injection file does exist, then the shower files should be specified as the input files
    injection_filename = f"{TAMBO_DATA_PATH}/{wildcards.injection_config}/injection/{wildcards.injection_config}_{wildcards.injection_simset}_{wildcards.injection_subsimset}.jld2"
    if not os.path.exists(injection_filename):
        return injection_filename
    else:
        shower_files = expand(f"{TAMBO_DATA_PATH}" + "/{{injection_config}}/showers/{{injection_simset}}_{{injection_subsimset}}/shower_{proposal_ids[0]}_{proposal_ids[1]}/particles/particles.parquet", proposal_ids=lambda wildcards: get_particle_ids(wildcards))
        return shower_files

rule make_hit_maps: # Note: rule currently configured so that all showers must be run, even if only a subset of them are needed for a specific him map file
    input:
        get_injection_files,
        array_config = lambda wildcards: f'{TAMBOSIM_PATH}/resources/configuration_examples/{wildcards.array_config}.toml'
    output:
        outfile = f"{TAMBO_DATA_PATH}/{{injection_config}}/hit_maps/{{array_config}}/hit_maps_{{injection_simset}}_{{injection_subsimset}}_{{hit_map_subset_id}}_{{hit_map_total_subsets}}.jld2"
    resources:
        cpus_per_task=1,
        mem_mb=8000,
        slurm_partition="sapphire,shared",
        runtime=240
    shell: 
       f"""
        julia {TAMBOSIM_PATH}/scripts/1_make_hit_maps/make_hit_map.jl \
        --array_config {{input.array_config}} \
        --injection_config {{wildcards.injection_config}} \
        --basedir {TAMBO_DATA_PATH}/{{wildcards.injection_config}} \
        --simfile {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/{{wildcards.injection_config}}_{{wildcards.injection_simset}}_{{wildcards.injection_subsimset}}.jld2 \
        --outfile {{output.outfile}} \
        --njob {{wildcards.hit_map_subset_id}} \
        --nparallel {{wildcards.hit_map_total_subsets}} \
        --simset {{wildcards.injection_simset}} \
        --subsimset {{wildcards.injection_subsimset}}
        """

rule combine_hit_map_files:
    input:
        # FIXME: update to handle different number of hit map files
        hit_map_files = expand(f"{TAMBO_DATA_PATH}" + "/{{injection_config}}/hit_maps/{{array_config}}/hit_maps_{{injection_simset}}_{{injection_subsimset}}_{idx}_100.jld2", idx=range(1,101))
    output:
        f"{TAMBO_DATA_PATH}/{{injection_config}}/hit_maps/{{array_config}}/hit_maps_{{injection_simset}}_{{injection_subsimset}}_full.jld2"
    resources:
        cpus_per_task=1,
        mem_mb=4000,
        slurm_partition="sapphire,shared",
        runtime=60
    shell:
        f"""
        julia {TAMBOSIM_PATH}/scripts/1_make_hit_maps/combine_hit_map_files.jl \
        --hit_map_directory {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/hit_maps/{{wildcards.array_config}}/ \
        --simset {{wildcards.injection_simset}} \
        --subsimset {{wildcards.injection_subsimset}} \
        """

rule do_triggering:
    input:
        f"{TAMBO_DATA_PATH}/{{injection_config}}/injection/{{injection_config}}_{{injection_simset}}_{{injection_subsimset}}.jld2",
        f"{TAMBO_DATA_PATH}/{{injection_config}}/hit_maps/{{array_config}}/hit_maps_{{injection_simset}}_{{injection_subsimset}}_full.jld2",
        trigger_config = lambda wildcards: f'{TAMBOSIM_PATH}/resources/configuration_examples/{wildcards.trigger_config}.toml'
    output:
        f"{TAMBO_DATA_PATH}/{{injection_config}}/triggered/{{array_config}}/{{trigger_config}}/triggered_events_{{injection_simset}}_{{injection_subsimset}}.jld2"
    resources:
        cpus_per_task=1,
        mem_mb=8000,
        slurm_partition="sapphire,shared",
        runtime=240
    shell: 
        f"""
        julia {TAMBOSIM_PATH}/scripts/2_trigger_events/do_triggering.jl \
        --simfile {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/injection/{{wildcards.injection_config}}_{{wildcards.injection_simset}}_{{wildcards.injection_subsimset}}.jld2 \
        --hitmapdir {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/hit_maps/{{wildcards.array_config}}/ \
        --simset {{wildcards.injection_simset}} \
        --subsimset {{wildcards.injection_subsimset}} \
        --trigger_config {{input.trigger_config}} \
        --outdir {TAMBO_DATA_PATH}/{{wildcards.injection_config}}/triggered/{{wildcards.array_config}}/{{wildcards.trigger_config}}/
        """

def get_hit_map_files(config):
    config = config + '.toml'
    with open(config) as f:
        config_dict = toml.load(f)
    hit_maps_dir = config_dict['hitmapdir']
    hit_maps_files = glob.glob(f'{hit_maps_dir}hit_maps_*.jld2')
    return hit_maps_files
